name=DFRobot_Mindplus_mPython
version=3.0.0
author=DFRobot
maintainer=DFRobot <support@dfrobot.com>
sentence=MindPlus mPython library for掌控板3.0
description=This library provides support for mPython掌控板3.0, including buttons, touch pads, RGB LEDs, buzzer, display, audio record/playback, and USB disk.
category=Sensors
url=https://www.dfrobot.com
architectures=esp32
includes=MPython.h

# ldflags=-Wl,--whole-archive "{runtime.platform.path}/libraries/DFRobot_Mindplus_MPython/src/audio/esp_audio_codec/lib/esp32s3/libesp_audio_codec.a" "{runtime.platform.path}/libraries/DFRobot_Mindplus_MPython/src/audio/esp_audio_codec/lib/esp32s3/libesp_audio_simple_dec.a" -Wl,--no-whole-archive
# dot_a_linkage=true
precompiled=true
ldflags=-lDFRobot_Mindplus_MPython